2020-12-29 17:51:14,747 ERROR: Exception on /auth/login [GET] [in /home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liza/PycharmProjects/microblog2/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/liza/PycharmProjects/microblog2/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/base.html", line 18, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2020-12-29 17:52:15,090 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:54]
2020-12-29 17:52:20,977 ERROR: Exception on /index [GET] [in /home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/liza/PycharmProjects/microblog2/app/main/routes.py", line 45, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/liza/PycharmProjects/microblog2/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/liza/PycharmProjects/microblog2/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2020-12-29 17:53:12,144 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:54]
2020-12-29 18:51:50,335 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:73]
